import { sqliteTable, text, integer, real } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';

export const startups = sqliteTable('startups', {
  id: text('id').primaryKey(),
  source: text('source').notNull(), // primary source: 'yc' | 'producthunt' | 'crunchbase'
  sources: text('sources', { mode: 'json' }).$type<string[]>().default([]), // all sources, e.g. ['yc', 'producthunt']
  externalId: text('external_id').notNull(),
  name: text('name').notNull(),
  nameRu: text('name_ru'),
  slug: text('slug').notNull(),
  website: text('website'),
  sourceUrl: text('source_url').notNull(),
  logoUrl: text('logo_url'),

  tagline: text('tagline'),
  taglineRu: text('tagline_ru'),
  description: text('description'),
  descriptionRu: text('description_ru'),

  tags: text('tags', { mode: 'json' }).$type<string[]>().default([]),
  industries: text('industries', { mode: 'json' }).$type<string[]>().default([]),
  tagsRu: text('tags_ru', { mode: 'json' }).$type<string[]>().default([]),

  // YC-specific
  batch: text('batch'),
  teamSize: integer('team_size'),
  status: text('status'),

  // Product Hunt-specific
  votesCount: integer('votes_count'),
  commentsCount: integer('comments_count'),
  dailyRank: integer('daily_rank'),
  weeklyRank: integer('weekly_rank'),

  // Crunchbase-specific
  fundingTotal: real('funding_total'),
  fundingStage: text('funding_stage'),
  foundedYear: integer('founded_year'),
  employeeRange: text('employee_range'),

  // Geo
  locations: text('locations', { mode: 'json' }).$type<string[]>().default([]),
  regions: text('regions', { mode: 'json' }).$type<string[]>().default([]),

  // Detailed analysis (from manual review)
  targetUser: text('target_user'),
  problemStatement: text('problem_statement'),
  solutionText: text('solution_text'),
  foundersText: text('founders_text'),
  foundersLinks: text('founders_links'),
  investorsText: text('investors_text'),
  fundingRounds: text('funding_rounds'),
  revenueText: text('revenue_text'),
  audienceText: text('audience_text'),

  // Scoring (legacy v1)
  scoreTotal: real('score_total').default(0),
  scoreDisruption: real('score_disruption').default(0),
  scoreScalability: real('score_scalability').default(0),
  scoreMarketSize: real('score_market_size').default(0),
  scoreRussiaBarriers: real('score_russia_barriers').default(0),
  scoreTraction: real('score_traction').default(0),
  scoreTimingRussia: real('score_timing_russia').default(0),
  scoreFounderStrength: real('score_founder_strength').default(0),

  // Scoring VENTURE-SCAN RF 2.0 (M²×T×A×B×P)^(1/6)×10
  scoreM: real('score_m'),
  scoreT: real('score_t'),
  scoreA: real('score_a'),
  scoreB: real('score_b'),
  scoreP: real('score_p'),
  scoreV2: real('score_v2'),

  launchedAt: text('launched_at'),
  createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
  updatedAt: text('updated_at').notNull().default(sql`(datetime('now'))`),
  translatedAt: text('translated_at'),
  scoredAt: text('scored_at'),
});

export const weeklyTop = sqliteTable('weekly_top', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  startupId: text('startup_id').notNull().references(() => startups.id),
  weekLabel: text('week_label').notNull(),
  rank: integer('rank').notNull(),
  scoreSnapshot: real('score_snapshot').notNull(),
  createdAt: text('created_at').default(sql`(datetime('now'))`),
});

export const monthlyTop = sqliteTable('monthly_top', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  startupId: text('startup_id').notNull().references(() => startups.id),
  monthLabel: text('month_label').notNull(),
  rank: integer('rank').notNull(),
  scoreSnapshot: real('score_snapshot').notNull(),
  createdAt: text('created_at').default(sql`(datetime('now'))`),
});

export const syncLog = sqliteTable('sync_log', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  source: text('source').notNull(),
  status: text('status').notNull(),
  recordsAdded: integer('records_added').default(0),
  recordsUpdated: integer('records_updated').default(0),
  errorMessage: text('error_message'),
  startedAt: text('started_at').notNull(),
  finishedAt: text('finished_at'),
});

export const newsSummaries = sqliteTable('news_summaries', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  periodLabel: text('period_label').notNull(), // e.g. '2026-W15'
  content: text('content').notNull(),          // markdown/text generated by Claude
  postsCount: integer('posts_count').notNull(),
  generatedAt: text('generated_at').notNull().default(sql`(datetime('now'))`),
});

export const news = sqliteTable('news', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  channel: text('channel').notNull(),
  externalId: text('external_id').notNull(),
  text: text('text').notNull(),
  imageUrl: text('image_url'),
  sourceUrl: text('source_url').notNull(),
  publishedAt: text('published_at').notNull(),
  createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
});

export type NewsSummary = typeof newsSummaries.$inferSelect;
export type Startup = typeof startups.$inferSelect;
export type NewStartup = typeof startups.$inferInsert;
export type NewsItem = typeof news.$inferSelect;
